all: clean fetch patch 
.PHONY: all

.PHONY: fetch
fetch:
	git clone https://github.com/shiftkey/desktop.git work

.PHONY: patch
patch:

.PHONY: install
install:

.PHONY: remove
remove:

.PHONY: clean
clean:
	rm -rf ./work